AprobacionesWeb/Core.Web/Controllers/BitacorasController.cs
using Core.Data.general;
using Core.Info.general;
using Core.Web.Helps;
using DevExpress.Web;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Core.Web.Controllers
{
    public class BitacorasController : Controller
    {
        #region Variables
        BITACORAS_DATA odata_bit = new BITACORAS_DATA();
        ORDEN_TRABAJO_DET_DATA odata_ot = new ORDEN_TRABAJO_DET_DATA();
        SUCURSAL_DATA odata_su = new SUCURSAL_DATA();
        ARINDEX_DATA odata_ar = new ARINDEX_DATA();
        #endregion

        #region Index
        public ActionResult Index()
        {
            FILTRO_INFO model = new FILTRO_INFO();
            return View(model);
        }
        [HttpPost]
        public ActionResult Index(FILTRO_INFO model)
        {
            model.ID = odata_bit.GetID(model.IdViaje, model.IdSucursal);
            return View(model);
        }
        #endregion

        #region SucursalBajoDemanda
        public ActionResult CmbSucursal()
        {
            FILTRO_INFO model = new FILTRO_INFO();
            return PartialView("_CmbSucursal", model);
        }
        public List<SUCURSAL_INFO> get_list_bajo_demanda_sucursal(ListEditItemsRequestedByFilterConditionEventArgs args)
        {
            return odata_su.get_list_bajo_demanda(args);
        }
        public SUCURSAL_INFO get_info_bajo_demanda_sucursal(ListEditItemRequestedByValueEventArgs args)
        {
            return odata_su.get_info_bajo_demanda(args);
        }
        #endregion

        #region ViajeBajoDemanda
        public ActionResult CmbViaje()
        {
            FILTRO_INFO model = new FILTRO_INFO();
            return PartialView("_CmbViaje", model);
        }
        public List<ARINDEX_INFO> get_list_bajo_demanda_viaje(ListEditItemsRequestedByFilterConditionEventArgs args)
        {
            return odata_ar.get_list_bajo_demanda(args,"2");
        }
        public ARINDEX_INFO get_info_bajo_demanda_viaje(ListEditItemRequestedByValueEventArgs args)
        {
            return odata_ar.get_info_bajo_demanda(args, "2");
        }
        #endregion

        #region Bitacora
        public ActionResult GridViewPartialBitacora(string BARCO = "", string VIAJE = "")
        {
            ViewBag.BARCO = BARCO;
            ViewBag.VIAJE = VIAJE;
            FILTRO_INFO model = new FILTRO_INFO { lst_bit = odata_bit.get_list(VIAJE, BARCO) };
            return PartialView("_GridViewPartialBitacora",model);
        }

        public ActionResult GridViewPartialBitacoraDet()
        {
            SessionFixed.ID = Request.Params["PKID"] != null ? Request.Params["PKID"] :"0";
            SessionFixed.LINEA = Request.Params["PKLINEA"] != null ? Request.Params["PKLINEA"]: "0";
            FILTRO_INFO model = new FILTRO_INFO { lst_bit = odata_bit.get_list_det(Convert.ToInt32(SessionFixed.ID), Convert.ToInt16(SessionFixed.LINEA)) };
            return PartialView("_GridViewPartialBitacoraDet", model);
        }
        public ActionResult EditingDelete(short LINEA_DETALLE)
        {
            odata_bit.DELETELINEA(Convert.ToInt32(SessionFixed.ID), Convert.ToInt16(SessionFixed.LINEA), LINEA_DETALLE);
            FILTRO_INFO model = new FILTRO_INFO { lst_bit = odata_bit.get_list_det(Convert.ToInt32(SessionFixed.ID), Convert.ToInt16(SessionFixed.LINEA)) };
            return PartialView("_GridViewPartialBitacoraDet", model);
        }
        #endregion

        #region Json
        public JsonResult GetTotalOrden(int OT = 0)
        {
            decimal valor = 0;

            valor = odata_ot.GetTotalOrden("OT", OT);

            return Json(valor, JsonRequestBehavior.AllowGet);
        }

        public JsonResult ADDLINEA(int ID = 0, short LINEA = 0, string ORDEN = "", string VALOROT = "")
        {
            decimal resultado = 0;
            VALOROT = VALOROT == "" ? "0" : VALOROT;
            NumberFormatInfo provider = new NumberFormatInfo();
            provider.NumberDecimalSeparator = ".";
            provider.NumberGroupSeparator = ",";
            provider.NumberGroupSizes = new int[] { 3 };
            if (odata_bit.ADDLINEA(new BITACORAS_INFO
            {
                ID = ID,
                LINEA = LINEA,
                NUMERO_ORDEN = ORDEN,
                VALOR = Convert.ToDecimal(VALOROT,provider)
            })) resultado = 1;

            return Json(resultado, JsonRequestBehavior.AllowGet);
        }
        #endregion
    }
}

AprobacionesWeb/Core.Web/Views/Bitacoras/Index.cshtml
@model Core.Info.general.FILTRO_INFO
@{
    ViewBag.Title = "Asignar OT a bitácora";
    if (Session["IdUsuario"] == null)
    {
        Response.Redirect("~/Account/Login");
    }
}
<script type="text/javascript">
    $(function () {
        $("#txtOrden").keyup(function () {
            GetTotalOrden();
        });
    })

    function MostrarModal(ID, LINEA) {
        $("#ID").val(ID);
        $("#LINEA").text(LINEA);
        $("#txtOrden").val(0);
        $("#txtValor").val(0);
        GridViewBitacoraDet.PerformCallback();
        $("#ModalDetalle").modal("show");
    }

    function GetTotalOrden() {
        var datos = {
            OT: $("#txtOrden").val()
        }
        $.ajax({
            type: 'POST',
            data: JSON.stringify(datos),
            url: '@Url.Action("GetTotalOrden", "Bitacoras", new { Area = ""})',
            async: false,
            bDeferRender: true,
            bProcessing: true,
            dataType: 'json',
            contentType: 'application/json; charset=utf-8',
            success: function (data) {
                $("#txtValor").val(data);
            },
            error: function (error) {
            }
        });
    }

    function ADDLINEA() {
        var valor = $("#txtValor").val();
        var ot = $("#txtOrden").val();
        if (valor != "" && valor != "0" && ot != "" && ot != "0") {
            var datos = {
                ID: $("#ID").val(),
                LINEA: $("#LINEA").text(),
                ORDEN: $("#txtOrden").val(),
                VALOROT: $("#txtValor").val()
            }
            $.ajax({
                type: 'POST',
                data: JSON.stringify(datos),
                url: '@Url.Action("ADDLINEA", "Bitacoras",new { Area = ""})',
                async: false,
                bDeferRender: true,
                bProcessing: true,
                dataType: 'json',
                contentType: 'application/json; charset=utf-8',
                success: function (data) {
                    if (data == 1) {
                        $("#txtOrden").val(0);
                        $("#txtValor").val(0);
                    }
                },
                error: function (error) {
                }
            });
            GridViewBitacoraDet.PerformCallback();
        }               
    }
</script>
@using (Html.BeginForm("Index", "Bitacoras", FormMethod.Post, new { @class = "form", @role = "form", @id = "myform" }))
{
    @Html.HiddenFor(q=>q.ID, new { @id = "ID"})

    <div class="modal fade" id="ModalDetalle" role="dialog">
        <div class="modal-dialog">
            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Linea # <label id="LINEA">0</label></h4>
                </div>
                <div class="modal-body">
                    <div class="col-md-6 form-group">
                        <label for="txtOrden"># Orden</label>
                        <input type="text" id="txtOrden" class="form-control" />
                    </div>
                    <div class="col-md-6 form-group">
                        <label for="txtValor">Valor</label>
                        <input type="text" id="txtValor" class="form-control" />
                    </div>
                    <div class="col-md-12">
                        <button type="button" class="btn btn-primary" onclick="ADDLINEA();">Agregar</button>
                    </div>
                    <div class="col-md-12">
                        @Html.Action("GridViewPartialBitacoraDet")
                    </div>                    
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
                </div>
                
            </div>
        </div>
    </div>

    <div class="box">
        <div class="box-header with-border">
            <div class="row">
                <div class="col-md-12">
                    <button type="submit" class="btn btn-primary">Aplicar filtros</button>
                </div>
            </div>
            <div class="box-tools pull-right">
                <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse">
                    <i class="fa fa-minus"></i>
                </button>
                <button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Remove">
                    <i class="fa fa-times"></i>
                </button>
            </div>
        </div>
        <div class="box-body">
            <div class="row">
                <div class="col-md-12">
                    <div class="form-group">
                        <label for="IdSucursal">Centro de costo</label>
                        @Html.Partial("_CmbSucursal", Model)
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="form-group">
                        <label for="IdViaje">Viaje</label>
                        @Html.Partial("_CmbViaje", Model)
                    </div>
                </div>
            </div>
        </div>
        <!-- /.box-body -->
    </div>

    <div class="box">
        <div class="box-header with-border">
            <h3 class="box-title">@ViewBag.Title</h3>
            <div class="box-tools pull-right">
                <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse">
                    <i class="fa fa-minus"></i>
                </button>
                <button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Remove">
                    <i class="fa fa-times"></i>
                </button>
            </div>
        </div>
        <div class="box-body">
            @Html.Action("GridViewPartialBitacora", new { BARCO = Model.IdSucursal, VIAJE = Model.IdViaje})
        </div>
        <!-- /.box-body -->
        <div class="box-footer">
            
        </div>
        <!-- /.box-footer-->
    </div>
}

AprobacionesWeb/Core.Web/Views/Bitacoras/_CmbSucursal.cshtml
@using System.Web.UI.WebControls;
@{
    var comboBox = Html.DevExpress().ComboBox(settings =>
    {
        settings.Name = "IdSucursal";
        settings.Width = Unit.Percentage(100);
        settings.Properties.DropDownWidth = Unit.Percentage(100);
        settings.Properties.DropDownStyle = DropDownStyle.DropDown;
        settings.CallbackRouteValues = new { Controller = "Bitacoras", Action = "CmbSucursal" };
        settings.Properties.CallbackPageSize = 15;
        settings.Properties.IncrementalFilteringMode = IncrementalFilteringMode.Contains;
        settings.Properties.TextField = "NOMBRE";
        settings.Properties.TextFormatString = "[{0}] {1}";
        settings.Properties.ValueField = "CODIGO";
        settings.Properties.ValueType = typeof(string);

        settings.Properties.Columns.Add("CODIGO", "Código", 30);
        settings.Properties.Columns.Add("NOMBRE", "Centro de costo", 70);

        settings.Properties.ClearButton.DisplayMode = ClearButtonDisplayMode.Never;
    })
    .BindList(new Core.Web.Controllers.BitacorasController().get_list_bajo_demanda_sucursal, new Core.Web.Controllers.BitacorasController().get_info_bajo_demanda_sucursal)
    .Bind(Model.IdSucursal);

}
@comboBox.GetHtml()

AprobacionesWeb/Core.Web/Views/Bitacoras/_CmbViaje.cshtml
@using System.Web.UI.WebControls;
@{
    var comboBox = Html.DevExpress().ComboBox(settings =>
    {
        settings.Name = "IdViaje";
        settings.Width = Unit.Percentage(100);
        settings.Properties.DropDownWidth = Unit.Percentage(100);
        settings.Properties.DropDownStyle = DropDownStyle.DropDown;
        settings.CallbackRouteValues = new { Controller = "Bitacoras", Action = "CmbViaje" };
        settings.Properties.CallbackPageSize = 15;
        settings.Properties.IncrementalFilteringMode = IncrementalFilteringMode.Contains;
        settings.Properties.TextField = "NOMBRE";
        settings.Properties.TextFormatString = "[{0}] {1}";
        settings.Properties.ValueField = "CODIGO";
        settings.Properties.ValueType = typeof(string);

        settings.Properties.Columns.Add("CODIGO", "Código", 30);
        settings.Properties.Columns.Add("NOMBRE", "Viaje", 70);

        settings.Properties.ClearButton.DisplayMode = ClearButtonDisplayMode.Never;
    })
    .BindList(new Core.Web.Controllers.BitacorasController().get_list_bajo_demanda_viaje, new Core.Web.Controllers.BitacorasController().get_info_bajo_demanda_viaje)
    .Bind(Model.IdViaje);

}
@comboBox.GetHtml()

AprobacionesWeb/Core.Web/Views/Bitacoras/_GridViewPartialBitacora.cshtml
@using System.Web.UI.WebControls;
@{
    var grid = Html.DevExpress().GridView(settings =>
    {
        settings.Name = "GridViewBitacoras";
        settings.CallbackRouteValues = new { Controller = "Bitacoras", Action = "GridViewPartialBitacora", BARCO = ViewBag.BARCO, VIAJE = ViewBag.VIAJE };
        settings.Width = Unit.Percentage(100);
        settings.KeyFieldName = "LINEA";

        //CConfiguracion responsive
        settings.SettingsAdaptivity.AdaptivityMode = GridViewAdaptivityMode.HideDataCellsWindowLimit;
        settings.SettingsAdaptivity.AdaptiveColumnPosition = GridViewAdaptiveColumnPosition.Right;
        settings.SettingsAdaptivity.AdaptiveDetailColumnCount = 1;
        settings.SettingsAdaptivity.AllowOnlyOneAdaptiveDetailExpanded = false;
        settings.SettingsAdaptivity.HideDataCellsAtWindowInnerWidth = 500;
        //Configuración scrolling y pager
        settings.Settings.HorizontalScrollBarMode = ScrollBarMode.Hidden;
        settings.Settings.VerticalScrollBarMode = ScrollBarMode.Visible;
        settings.Settings.VerticalScrollableHeight = 500;
        settings.SettingsPager.Visible = true;
        settings.SettingsPager.PageSize = 10;
        settings.SettingsPager.Mode = GridViewPagerMode.ShowPager;
        settings.SettingsPager.AlwaysShowPager = true;
        //Configuración filtro por columna
        settings.SettingsBehavior.AllowSelectByRowClick = true;

        //Evento para pintar de rojo las filas anuladas
        settings.HtmlRowPrepared = (s, e) =>
        {
            if (Convert.ToInt32(e.GetValue("CANTLINEAS")) > 0)
            {
                e.Row.ForeColor = System.Drawing.Color.Blue;
            }
        };
        settings.Columns.Add("LINEA", "#").Width = Unit.Percentage(10);
        settings.Columns.Add("DESCRIPCION", "Descripción").Width = Unit.Percentage(40);
        settings.Columns.Add("CONTRATISTA", "Contratista").Width = Unit.Percentage(30);
        
        settings.Columns.Add(column =>
        {
            column.Caption = "OT";
            column.Width = Unit.Percentage(10);
            column.UnboundType = DevExpress.Data.UnboundColumnType.String;
            column.SetDataItemTemplateContent(c =>
            {
                Html.DevExpress().Button(settingsBtn =>
                {
                    var ID = DataBinder.Eval(c.DataItem, "ID");
                    var LINEA = DataBinder.Eval(c.DataItem, "LINEA");
                    settingsBtn.Name = "btn" + LINEA;
                    settingsBtn.Text = "OT";
                    settingsBtn.ClientSideEvents.Click = "function(s, e) {MostrarModal('" + ID + "','" + LINEA + "');}";
                }).Render();
            });
        });
    });
}
@grid.Bind(Model.lst_bit).GetHtml()

AprobacionesWeb/Core.Web/Views/Bitacoras/_GridViewPartialBitacoraDet.cshtml
@using System.Web.UI.WebControls;
@{
    var grid = Html.DevExpress().GridView(settings =>
    {
        settings.Name = "GridViewBitacoraDet";
        settings.CallbackRouteValues = new { Controller = "Bitacoras", Action = "GridViewPartialBitacoraDet" };
        settings.Width = Unit.Percentage(100);
        settings.KeyFieldName = "LINEA_DETALLE";

        settings.SettingsPager.Visible = true;
        settings.Settings.ShowGroupPanel = false;
        settings.Settings.ShowFilterRow = true;

        settings.SettingsEditing.Mode = GridViewEditingMode.EditFormAndDisplayRow;
        //settings.SettingsEditing.UpdateRowRouteValues = new { Controller = "Bitacoras", Action = "EditingUpdate", Area = "" };
        settings.SettingsEditing.DeleteRowRouteValues = new { Controller = "Bitacoras", Action = "EditingDelete", Area = "" };

        settings.CommandColumn.Visible = true;
        settings.CommandColumn.ShowNewButton = false;
        settings.CommandColumn.ShowEditButton = false;
        settings.CommandColumn.ShowDeleteButton = true;

        settings.SettingsContextMenu.Enabled = true;
        settings.SettingsContextMenu.RowMenuItemVisibility.NewRow = false;
        settings.SettingsContextMenu.RowMenuItemVisibility.EditRow = false;
        settings.SettingsBehavior.EnableCustomizationWindow = true;

        //Configuración click derecho
        settings.SettingsContextMenu.Enabled = true;
        settings.SettingsBehavior.EnableCustomizationWindow = true;
        settings.SettingsContextMenu.EnableRowMenu = DefaultBoolean.True;

        //CConfiguracion responsive
        settings.SettingsAdaptivity.AdaptivityMode = GridViewAdaptivityMode.HideDataCellsWindowLimit;
        settings.SettingsAdaptivity.AdaptiveColumnPosition = GridViewAdaptiveColumnPosition.Right;
        settings.SettingsAdaptivity.AdaptiveDetailColumnCount = 1;
        settings.SettingsAdaptivity.AllowOnlyOneAdaptiveDetailExpanded = false;
        settings.SettingsAdaptivity.HideDataCellsAtWindowInnerWidth = 500;

        settings.Columns.Add("LINEA_DETALLE", "#").Width = Unit.Percentage(20);
        settings.Columns.Add("NUMERO_ORDEN", "# Orden").Width = Unit.Percentage(20);        
        settings.Columns.Add(c =>
        {
            c.Caption = "Valor";
            c.FieldName = "VALOR";
            c.Width = Unit.Percentage(40);
            c.PropertiesEdit.DisplayFormatString = "{0:N2}";
        });

        settings.ClientSideEvents.BeginCallback = "function(s, e) { e.customArgs['PKID'] = $('#ID').val(); e.customArgs['PKLINEA'] = $('#LINEA').text(); }";
        settings.ClientSideEvents.EndCallback = "function(s,e){GridViewBitacoras.PerformCallback();}";
    });
}
@grid.Bind(Model.lst_bit).GetHtml()